package com.github.am4dr.rokusho.util

import javafx.beans.property.SimpleListProperty
import javafx.collections.FXCollections
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test

class UtilsTest {
    @Test
    @DisplayName("ListProperty generated by no args SimpleListProperty() is not modifiable")
    fun modifySimpleListProperty() {
        assertThrows<UnsupportedOperationException>(UnsupportedOperationException::class.java) {
            SimpleListProperty<Any>().add("test")
        }
    }
    @Test
    @DisplayName("ListProperty generated by createEmptyListProperty() is modifiable")
    fun modifyEmptyListProperty() {
        createEmptyListProperty<Any>().add("test")
    }

    @Nested
    inner class ObservableMapToObservableListTest {
        @Test
        fun simpleExample() {
            val map = FXCollections.observableMap(mutableMapOf(1 to "1", 2 to "2"))
            val list = toObservableList(map)

            assertEquals(2, list.size)
            assertTrue(list.containsAll(listOf("1", "2")))

            map.remove(2)
            assertEquals(1, list.size)
            assertTrue(list.containsAll(listOf("1")))

            map[10] = "10"
            map[1]  = "100"
            assertEquals(2, list.size)
            assertTrue(list.containsAll(listOf("100", "10")))
        }
    }
}
